INSERT INTO USER_DETAILS (NAME, BIRTH_DATE) VALUES ('Avar','2002-12-12');
INSERT INTO USER_DETAILS (NAME, BIRTH_DATE) VALUES ('Harsit Beta','2002-12-12');

INSERT INTO POST (DESCRIPTION, USERS_ID) VALUES ('Insta',1);
INSERT INTO POST (DESCRIPTION, USERS_ID) VALUES ('Tinder',2);
